name: Build and release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build_OOADump:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout self
        uses: actions/checkout@v7

      - name: Get latest release tag
        shell: bash
        run:  |
          tag=$(gh release view --repo O-Robotic/OOADump --json tagName -q .tagName)
          if [ -z "$tag" ]; then
            echo "Could not get latest release tag" >&2
            exit 1
          fi
          echo "tag=$tag" >> $GITHUB_ENV

      - name: Find release in cache
        id: cache-ooadump
        uses: actions/cache@v6
        with:
          path: OOADump
          key: ooadump-${{env.tag}}

      - name: Build OOADump
        if: steps.cache-ooadump.outputs.cache-hit != 'true'
        uses: ./.github/actions/build_tools
        with:
          repo: O-Robotic/OOADump
          tag: ${{env.tag}}
          clone_dir: ${{ github.workspace }}/ooadump_src
          runtime_path: ${{ github.workspace }}

      - name: Save to cache
        if: steps.cache-ooadump.outputs.cache-hit != 'true'
        uses: actions/cache/save@v6
        with:
          path: OOADump
          key: ooadump-${{env.tag}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ooadump
          path: OOADump
          if-no-files-found: error
          retention-days: 7


  build_BinPatch:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout self
      uses: actions/checkout@v7

    - name: Get latest release tag
      shell: bash
      run:  |
        tag=$(gh release view --repo O-Robotic/BinPatch --json tagName -q .tagName)
        if [ -z "$tag" ]; then
          echo "Could not get latest release tag" >&2
          exit 1
        fi
        echo "tag=$tag" >> $GITHUB_ENV

    - name: Find release in cache
      id: cache-binpatch
      uses: actions/cache@v6
      with:
        path: BinPatch
        key: binpatch-${{env.tag}}

    - name: Build BinPatch
      if: steps.cache-binpatch.outputs.cache-hit != 'true'
      uses: ./.github/actions/build_tools
      with:
        repo: O-Robotic/BinPatch
        tag: ${{env.tag}}
        clone_dir: ${{ github.workspace }}/binpatch_src
        runtime_path: ${{ github.workspace }}

    - name: Save to cache
      if: steps.cache-binpatch.outputs.cache-hit != 'true'
      uses: actions/cache/save@v6
      with:
        path: BinPatch
        key: binpatch-${{env.tag}}

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: binpatch
        path: BinPatch
        if-no-files-found: error
        retention-days: 7

  unpack_and_patch:
    needs: [build_OOADump, build_BinPatch]

    runs-on: ubuntu-latest
    env:
      OOA_UNPACK_KEY: ${{ secrets.OOA_UNPACK_KEY }}

    steps:
      - name: Checkout self
        uses: actions/checkout@v7

      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: Decrypt Executable
        run: | 
          chmod +x OOADump
          ./OOADump --outputfile r5apex.unpacked.exe r5apex.exe

      - name: Create Output Dir
        run: mkdir out

      - name: Patch Executable
        run: |
          chmod +x BinPatch
          ./BinPatch -input r5apex.unpacked.exe -patch r5apex.yaml -output out/r5apex.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: r5apex
          path: out/r5apex.exe
          if-no-files-found: error
          retention-days: 7

  release:
    needs: unpack_and_patch
    runs-on: ubuntu-latest

    env:
      TAG: ${{ inputs.release_tag || github.ref_name }}

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          pattern: r5apex
          merge-multiple: true
          path: rel

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.TAG }}
          files: rel/*
    